### ISSUE TITLE
Sports Rule Books

### ISSUE THREAD

**Issue by mduraney** [robgray2000/MiniProject1#1]
Hi there! My idea is to do text analysis on two different rule books for two different sports in order to see the commonly used words between sports rule books any maybe the different kinds of words used between two different sports.

I have been trying to find some solid rule books to do analysis on and these are the two sources I've landed on for right now if it all goes well. One is the college football rule book and the other is the college baseball rule book.

https://www.dfoa.com/wp-content/uploads/2021/07/2021-NCAA-FB-Rulebook.pdf

https://macumpires.org/pdf/2021-22-ncaa-baseball-rules.pdf

My main concern is doing the text analysis on PDFs rather than html since html was used in the MiniProject1 examples.

**Comment by robgray2000** [comment]
That is a very interesting idea and I am excited to see the differences between the two. I am also very interested to see how this might be done on pdf files instead of the html files.
